### PR TITLE
GH-725: RecordContext should provide access to lastFailureReason

### PR DESCRIPTION
**Pull request by jvissers**
Exposes `lastFailureReason` from `Recordcontext`

### CODE REVIEW

**Comment by jvissers** [comment]
I have signed the agreement.

**Comment by rkolesnev** [comment]
Hi @jvissers - is there a mismatch between email configured on your GH client / to do the commit and configured on your GH account? I think CLA bot is cross-checking on that - if they don't match - that may trip it over.
Can you please add the change to the CHANGELOG.adoc - it is a small change - but i think it is a useful one - so would be good to highlight in the changelog.

Thanks.

**Comment by rkolesnev** [comment]
Here is a GH troubleshooting link for account / local account setup - if that helps [troubleshooting-commits](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user)
Looking at the commit here - your username is not resolved as a link to GH user - there may be something missing in your local account setup - potentially that prevents CLA bot from working properly - as it cant resolve author on the commit to your GH user.

**Comment by jvissers** [comment]
I've updated changelog, updated the git config for this project locally and
pushed my changes.

Apparently still not everything is working as desired. I've followed the
link for troubleshooting-commits, but that doesn't seem to reflect what I'm
seeing.

For one this ("over blue ? to the right of the username") as gets mentioned
here: "To read a message about why the commit is not linked, hover over the
blue?  to the right of the username.", is not showing. What else can I do?

**Comment by rkolesnev** [comment]
could you please try to squash the commits on your branch or reset and recommit and then force push the changes?

Basically the first commit still has your oracle email associated with it - the local changes are not retrospective so they only applied to the 2nd commit (change to the changelog).

I am hoping that force-push with new commit(s) that have updated email - will let the check to re-evaluate properly.
Alternatively - new PR would need to be created - and should go through fine as long as commits in it are using your Gmail email.

Thanks.

**Pull request closed without merging**
