### PR TITLE
fix: NullPointerException on partitions revoked (#757)

### PR DESCRIPTION
**Pull request by sangreal**
Description...
The race condition happens when there are partition revoked right after partition is assigned, and there are existing `incompleteOffsets`. 

1. partition assigned and `incompleteOffsets` existed
2. right before begin to poll and process messages, it got revoked
3. the `processingShard` has no data yet
4. when revoked, try to delete `entries` with records from `incompleteOffsets`, no such record in `entries`

### Checklist

- [x] Documentation (if applicable)
- [ ] Changelog

### CODE REVIEW

**Comment by rkolesnev** [comment]
@sangreal - were you able to reproduce the issue? Could you add a test that reproduces it and tests for regression?

**Comment by sangreal** [comment]
> @sangreal - were you able to reproduce the issue? Could you add a test that reproduces it and tests for regression?

@rkolesnev Thanks for the comment, I update the description and more details and UT is added.

**Comment by rkolesnev** [comment]
Hey @sangreal - thanks, can you please run license check / update license headers in updated / new files?
Refer to build output - https://confluentinc.semaphoreci.com/workflows/a37eff87-3a4f-493c-aa74-89d56d9a557a?pipeline_id=af6b4e93-5d9e-4e1e-9467-d0ee07c953ee.

**Comment by sangreal** [comment]
@rkolesnev thanks, I updated pr and please help trigger again.

**Review by rkolesnev — APPROVED** [review]

**Pull request merged**
