### PR TITLE
Make parallel consumer java ee compliant

### PR DESCRIPTION
**Pull request by System0X**
As far as I looked I only found two places where ExecutorService or ThreadFactory is being used.

### CODE REVIEW

**Review by astubbs — CHANGES_REQUESTED** [review]
Thanks! Can you change the log level to debug and include the exception message.

**Comment by astubbs** [comment]
I’m not that familiar with EE anymore - should the string be configurable with a default?

**Comment by System0X** [comment]
> should the string be configurable with a default?

Yes, it should. Is there a default way you deal with it?

**Comment by astubbs** [comment]
Yeah take a look in the options class.

**Comment by System0X** [comment]
The changes have been made😄

**Review by astubbs — APPROVED** [review]

**Comment by astubbs** [comment]
Thanks!

**Pull request merged**
